# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'flashlight' do

source 'https://cdn.cocoapods.org/'


# 网络
pod 'AFNetworking',           '4.0.1'

# 本地工具库
pod 'lhsCommonMethod', :podspec => '../lhsCommonMethod.podspec'

end
